//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Followers
    {
        public long id { get; set; }
        public Nullable<long> first { get; set; }
        public Nullable<long> second { get; set; }
        public Nullable<int> num_occurrences { get; set; }
    }
}
